name: mlprivacy
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.11.*
  - pip
  - pip:
    - torchvision
    - scikit-learn
    - matplotlib
    - tqdm
    - numpy
    - torch
    - scipy
    - pandas
    - hdbscan
    - cudatoolkit